import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'english_ln': {
          'Welcome': 'Welcome',
          'Convert Image to PDF': 'Convert Image to PDF',
          'Compress Images': 'Compress Images ',
          'Use Now': 'Use Now',
          'PDF Images': 'PDF Images',
          'Compressed Images': 'Compressed Images',
          'Camera': 'Camera',
          'Storage': 'Storage',
          'Done': 'Done',
          'Select Images from': 'Select Images from',
          'No image selected': 'No image selected',
          'limit exceeded': 'limit exceeded ',
          'OK': 'OK',
          'Crop Image': 'Crop Image',
          'Converted Images': 'Converted Images',
          'enter a valid name': 'enter a valid name',
          'No image selected, kindly choose images':
              'No image selected, kindly choose images',
          'File name': 'File name',
          'Page Size': 'Page Size',
          'Orientation': 'Orientation',
          'Cancel': 'Cancel',
          'Convert': 'Convert',
          'File converted Successfully': 'File converted Successfully',
          'No Converted PDFs Available': 'No Converted PDFs Available',
          'File converted successfully': 'File converted successfully',
          'Do you want to delete "this" file?':
              'Do you want to delete "this" file?',
          'Do you want to delete "this" Image?':
              'Do you want to delete "this" Image?',
          'YES': 'YES ',
          'NO': 'NO',
          'Images saved Successfully in "compressedImages" in downloads':
              'Images saved Successfully in "compressedImages" in downloads',
          'No Compressed Image Available': 'No Compressed Image Available',
          'Select Images': 'Select Images',
          'Compress': 'Compress ',
          'Images Compressed Successfully': 'Images Compressed Successfully',
          'Privacy Policy': 'Privacy Policy',
          'Share ': 'Share',
          'Change Language': 'Change Language'
        },
        'german_ln': {
          'Welcome': 'Herzlich willkommen',
          'Convert Image to PDF': 'Bild in PDF konvertieren',
          'Compress Images': 'Bilder komprimieren',
          'Use Now': 'Jetzt \n verwenden',
          'PDF Images': 'PDF-Bilder',
          'Compressed Images': 'Komprimierte Bilder',
          'Camera': 'Kamera',
          'Storage': 'Lager',
          'Done': 'Erledigt',
          'Select Images from': 'Wählen Sie Bilder aus',
          'No image selected': 'Kein Bild ausgewählt',
          'limit exceeded': 'Limit überschritten',
          'OK': 'OK',
          'Converted Images': 'Konvertierte Bilder',
          "enter a valid name": "Geben Sie einen gültigen Namen ein",
          "Crop Image": "Bild zuschneiden",
          'No image selected, kindly choose images':
              'Kein Bild ausgewählt, bitte Bilder auswählen',
          'File name': 'Dateiname',
          'Page Size': 'Seitengröße',
          'Orientation': 'Orientierung',
          'Cancel': 'Stornieren',
          'Convert': 'Konvertieren',
          'File converted Successfully': 'Datei erfolgreich konvertiert',
          'No Converted PDFs Available': 'Keine konvertierten PDFs verfügbar',
          'File converted successfully': 'Datei erfolgreich konvertiert',
          'Do you want to delete this file?':
              'Möchten Sie diese Datei löschen?',
          'Do you want to delete this Image?':
              'Möchten Sie dieses Bild löschen?',
          'YES': 'JA',
          'NO': 'NEIN',
          'Images saved Successfully in "compressedImages" in downloads':
              'Bilder erfolgreich in "compressedImages“ in Downloads gespeichert',
          'No Compressed Image Available': 'Kein komprimiertes Bild verfügbar',
          'Select Images': 'Bilder auswählen',
          'Compress': 'komprimieren',
          'Images Compressed Successfully': 'Bilder erfolgreich komprimiert',
          'Privacy Policy': 'Datenschutzrichtlinie',
          'Share': 'Teilen',
          'Change Language': 'Sprache ändern'
        },
        'Korean_ln': {
          'Welcome': '환영',
          'Convert Image to PDF': '이미지를 PDF로 변환',
          'Compress Images': '이미지 압축',
          'Use Now': '지금 사용',
          'PDF Images': 'PDF 이미지',
          'Compressed Images': '압축 이미지',
          'Camera': '카메라',
          'Storage': '저장',
          'Done': '완료',
          'Select Images from': '다음에서 이미지 선택',
          'No image selected': '선택한 이미지 없음',
          'limit exceeded': '한도 초과',
          'OK': '좋아요',
          'Converted Images': '변환된 이미지',
          'enter a valid name': '유효한 이름 입력',
          'Crop Image': '이미지 자르기',
          'No image selected, kindly choose images':
              '선택한 이미지가 없습니다. 이미지를 선택하세요',
          'File name': '파일 이름',
          'Page Size': '페이지 크기',
          'Orientation': '방향',
          'Cancel': '취소',
          'Convert': '변환',
          'File converted Successfully': '파일 변환 성공',
          'No Converted PDFs Available': '변환된 PDF 없음',
          'File converted successfully ': '파일이 성공적으로 변환되었습니다',
          'Do you want to delete this file?': '이 파일을 삭제하시겠습니까?',
          'Do you want to delete this Image?': '이 이미지를 삭제하시겠습니까?',
          'YES': '예',
          'NO': '아니요',
          'Images saved Successfully in "compressedImages" in downloads':
              '다운로드의 "compressedImages"에 이미지가 성공적으로 저장되었습니다',
          'No Compressed Image Available': '사용 가능한 압축 이미지 없음',
          'Select Images': '이미지 선택',
          'Compress': '압축',
          'Images Compressed Successfully': '이미지 압축 성공',
          'Privacy Policy': '개인정보 보호정책',
          'Share': '공유',
          'Change Language': '언어 변경'
        },
        'italian_ln': {
          'Welcome': 'Benvenuto',
          'Convert Image to PDF': 'Convertire immagini in PDF',
          'Compress Images': 'Comprimere immagini',
          'Use Now': 'Usa ora',
          'PDF Images': 'Immagini in PDF',
          'Compressed Images': 'Immagini compresse',
          'Camera': 'Fotocamera',
          'Storage': 'Archiviazione',
          'Done': 'Fatto',
          'Select Images from': 'Selezionare le immagini da',
          'No image selected': 'Nessuna immagine selezionata',
          'limit exceeded': 'limite superato',
          'OK': 'OK',
          'Converted Images': 'Immagini convertite',
          'enter a valid name': 'inserire un nome valido',
          'Crop Image': 'Ritagliare immagine',
          'No image selected, kindly choose images':
              'Nessuna immagine selezionata, si prega di scegliere le immagini',
          'File name': 'Nome file',
          'Page Size': 'Dimensione pagina',
          'Orientation': 'Orientamento',
          'Cancel': 'Annulla',
          'Convert': 'Convertire',
          'File converted Successfully': 'File convertito con successo',
          'No Converted PDFs Available': 'Nessun PDF convertito disponibile',
          'File converted successfully': 'File convertito con successo',
          'Do you want to delete this file?':
              'Si desidera eliminare questo file?',
          'Do you want to delete this Image?':
              'Si desidera eliminare questa immagine?',
          'YES': 'SÌ',
          'NO': 'NO',
          'Images saved Successfully in "compressedImages" in downloads':
              'Immagini salvate con successo in "compressedImages" in download',
          'No Compressed Image Available':
              'Nessuna immagine compressa disponibile',
          'Select Images': 'Selezionare le immagini',
          'Compress': 'Comprimere',
          'Images Compressed Successfully': 'Immagini compresse con successo',
          'Privacy Policy': 'Informativa sulla privacy',
          'Share': 'Condividi',
          'Change Language': 'Cambia lingua'
        },
        'Indonesian_ln': {
          'Welcome': 'Selamat datang',
          'Convert Image to PDF': 'Konversi Gambar ke PDF',
          'Compress Images': 'Kompres Gambar',
          'Use Now': 'Gunakan\n Sekarang',
          'PDF Images': 'Gambar PDF',
          'Compressed Images': 'Gambar Terkompresi',
          'Camera': 'Kamera',
          'Storage': 'Penyimpanan',
          'Done': ' Selesai',
          'Select Images from': 'Pilih Gambar dari',
          'No image selected': 'Tidak ada gambar yang dipilih',
          'limit exceeded': 'batas terlampaui',
          'OK': 'OKE',
          'Converted Images': 'Gambar yang Dikonversi',
          'enter a valid name': 'masukkan nama yang valid',
          'Crop Image': 'Pangkas Gambar',
          'No image selected, kindly choose images':
              'Tidak ada gambar yang dipilih, silakan pilih gambar',
          'File name': 'Nama file',
          'Page Size': 'Ukuran Halaman',
          'Orientation': 'Orientasi',
          'Cancel': 'Batal',
          'Convert': 'Konversi',
          'File converted Successfully':
              'File berhasil dikonversi dengan sukses',
          'No Converted PDFs Available':
              'Tidak Ada PDF yang Dikonversi Tersedia',
          'File converted successfully': 'File berhasil dikonversi',
          'Do you want to delete this file?':
              'Apakah Anda ingin menghapus file ini?',
          'Do you want to delete this Image?':
              'Apakah Anda ingin menghapus Gambar ini?',
          'YES': 'YA',
          'NO': 'TIDAK',
          'Images saved Successfully in "compressedImages" in downloads':
              'Gambar berhasil disimpan di "compressedImages" dalam unduhan',
          'No Compressed Image Available':
              'Tidak Ada Gambar Terkompresi yang Tersedia',
          'Select Images': 'Pilih Gambar',
          'Compress': 'Kompres',
          'Images Compressed Successfully': 'Gambar Berhasil Dikompresi',
          'Privacy Policy': 'Kebijakan Privasi',
          'Share': 'Bagikan',
          'Change Language': 'Ubah Bahasa'
        },
        'Japanese_ln': {
          'Welcome': 'ようこそ',
          'Convert Image to PDF': '画像をPDFに変換',
          'Compress Images': '画像を圧縮する',
          'Use Now': '今すぐ使用する',
          'PDF Images': 'PDF画像',
          'Compressed Images': '圧縮画像',
          'Camera': 'カメラ',
          'Storage': 'ストレージ',
          'Done': '完了',
          'Select Images from': '画像を選択',
          'No image selected': '画像が選択されていない',
          'limit exceeded': '制限超過',
          'OK': 'わかりました',
          'Converted Images': '変換された画像',
          'enter a valid name': '有効な名前を入力してください',
          'Crop Image': '画像を切り抜く',
          'No image selected, kindly choose images': '画像が選択されていません',
          'File name': 'ファイル名',
          'Page Size': 'ページサイズ',
          'Orientation': '向き',
          'Cancel': 'キャンセル',
          'Convert': '変換する',
          'File converted Successfully': 'ファイルは正常に変換されました',
          'No Converted PDFs Available': '変換されたPDFはありません',
          'File converted successfully': 'ファイルは正常に変換されました',
          'Do you want to delete this file?': 'このファイルを削除しますか？',
          'Do you want to delete this Image?': 'この画像を削除しますか？',
          'YES': 'はい',
          'NO': 'いいえ',
          'Images saved Successfully in "compressedImages" in downloads':
              '  ダウンロードの "compressedImages "に正常に保存された画像',
          'No Compressed Image Available': '圧縮画像がありません',
          'Select Images': '画像を選択',
          'Compress': '圧縮する',
          'Images Compressed Successfully': '正常に圧縮された画像',
          'Privacy Policy': 'プライバシーポリシー',
          'Share': '共有',
          'Change Language': '言語を変更'
        },
        'Russian_ln': {
          'Welcome   ': 'Добро пожаловать',
          'Convert Image to PDF': 'конвертировать в pdf',
          'Compress Images': 'Сжатие изображений',
          'Use Now': 'Использовать\nсейчас',
          'PDF Images': 'Изображения PDF',
          'Compressed Images': 'Сжатые изображения',
          'Camera': 'Камера',
          'Storage': 'Хранилище',
          'Done': 'Готово',
          'Select Images from': 'Выбрать изображения из',
          'No image selected': 'Изображение не выбрано',
          'limit exceeded': 'превышен лимит',
          'OK': 'ХОРОШО',
          'Converted Images': 'Преобразованные изображения',
          'enter a valid name': 'введите правильное имя',
          'Crop Image': 'Обрезать изображение',
          'No image selected, kindly choose images':
              'Изображение не выбрано, пожалуйста, выберите изображение',
          'File name': 'Имя файла',
          'Page Size': 'Размер страницы',
          'Orientation': 'Ориентация  ',
          'Cancel': 'Отменить',
          'Convert': 'Конвертировать',
          'File converted Successfully': 'Файл успешно преобразован',
          'No Converted PDFs Available':
              'Нет доступных преобразованных PDF-файлов',
          'File converted successfully': 'Файл успешно конвертирован',
          'Do you want to delete this file?': 'Вы хотите удалить этот файл?',
          'Do you want to delete this Image?':
              'Хотите ли Вы удалить это изображение?',
          'YES': 'ДА',
          'NO': 'НЕТ',
          'Images saved Successfully in "compressedImages" in downloads':
              'Изображения успешно сохранены в "compressedImages" в загрузках',
          'No Compressed Image Available': 'Нет доступных сжатых изображений',
          'Select Images': 'Выберите изображения',
          'Compress': 'Сжать',
          'Images Compressed Successfully': 'Изображения успешно сжаты',
          'Privacy Policy': 'Политика конфиденциальности',
          'Share': 'Поделиться',
          'Change Language': 'Изменить язык'
        },
        'Portuguese_ln': {
          'Welcome': 'Bem-vindo',
          'Convert Image to PDF': 'Converter imagem em PDF',
          'Compress Images': 'Comprimir imagens',
          'Use Now': 'Usar agora',
          'PDF Images': 'Imagens PDF',
          'Compressed Images': 'Imagens comprimidas',
          'Camera': 'Câmara',
          'Storage': 'Armazenamento',
          'Done': 'Concluído',
          'Select Images from': 'Selecionar imagens de',
          'No image selected': 'Nenhuma imagem selecionada',
          'limit exceeded': 'limite excedido',
          'OK': 'OK',
          'Converted Images': 'Imagens convertidas',
          'enter a valid name': 'introduzir um nome válido',
          'Crop Image': 'Cortar imagem',
          'No image selected, kindly choose images':
              'Nenhuma imagem selecionada, por favor escolha as imagens',
          'File name': 'Nome do ficheiro',
          'Page Size': 'Tamanho da página',
          'Orientation ': 'Orientação',
          'Cancel': 'Cancelar',
          'Convert': 'Converter',
          'File converted Successfully': 'Ficheiro convertido com sucesso',
          'No Converted PDFs Available': 'Não há PDFs convertidos disponíveis',
          'File converted successfully': 'Ficheiro convertido com sucesso',
          'Do you want to delete this file?': 'Pretende apagar este ficheiro?',
          'Do you want to delete this Image?': 'Pretende apagar esta imagem?',
          'YES': 'SIM',
          'NO': 'NÃO',
          'Images saved Successfully in "compressedImages" in downloads':
              'Imagens guardadas com êxito em "compressedImages" nas transferências',
          'No Compressed Image Available':
              'Nenhuma imagem comprimida disponível',
          'Select Images': 'Selecionar imagens',
          'Compress': 'Comprimir',
          'Images Compressed Successfully': 'Imagens comprimidas com sucesso',
          'Privacy Policy': 'Política de privacidade',
          'Share': 'Partilhar',
          'Change Language': 'Alterar Idioma'
        },
        'Spanish_ln': {
          'Welcome': 'Bienvenido',
          'Convert Image to PDF': 'Convertir imagen a PDF',
          'Compress Images': 'Comprimir imágenes',
          'Use Now': 'Usar ahora',
          'PDF Images ': 'Imágenes PDF',
          'Compressed Images': 'Imágenes comprimidas',
          ' Camera': 'Cámara',
          ' Storage': 'Almacenamiento',
          ' Done': 'Hecho',
          'Select Images from': 'Seleccionar imágenes de',
          'No image selected': 'Ninguna imagen seleccionada',
          'limit exceeded': 'Límite excedido  ',
          'OK': 'DE ACUERDO',
          'Converted Images': 'Imágenes convertidas',
          'enter a valid name': 'introduzca un nombre válido',
          'Crop Image': 'Recortar imagen',
          'No image selected, kindly choose images':
              'No hay imagen seleccionada, por favor elija imágenes',
          'File name': 'Nombre de archivo',
          'Page Size': 'Tamaño de página',
          'Orientation': 'Orientación',
          'Cancel': 'Cancelar',
          'Convert': 'Convertir',
          'File converted Successfully': 'Archivo convertido correctamente',
          'No Converted PDFs Available':
              'No hay archivos PDF convertidos disponibles',
          'File converted successfully': 'Archivo convertido correctamente',
          'Do you want to delete this file?': '¿Desea eliminar este archivo?',
          'Do you want to delete this Image?': '¿Desea eliminar esta imagen?',
          'YES': 'SÍ',
          'NO': 'NO',
          'Images saved Successfully in "compressedImages" in downloads':
              'Imágenes guardadas con éxito en "compressedImages" en descargas',
          'No Compressed Image Available':
              'No hay imágenes comprimidas disponibles',
          'Select Images': 'Seleccionar imágenes',
          'Compress': 'Comprimir',
          'Images Compressed Successfully':
              'Imágenes comprimidas correctamente',
          'Privacy Policy': 'Política de privacidad',
          'Share': 'Compartir',
          'Change Language': 'Cambiar Idioma'
        }
      };
}
